# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  
  config.vm.define "virtualbox" do |vbox|
    vbox.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    vbox.vm.box = "ubuntu/xenial64"
    vbox.vm.network "forwarded_port", guest: 80, host: 8081
    vbox.vm.network "forwarded_port", guest: 443, host: 1443
    vbox.vm.network "forwarded_port", guest: 4443, host: 4443
    vbox.vm.network "forwarded_port", guest: 8443, host: 8443  
    vbox.vm.provision :ansible do |ansible|
      ansible.playbook = "playbook.yml"
      #ansible.tags = ['docker']
      #ansible.tags = ['deploy-stack']
    end
    vbox.vm.provision "shell", inline: "echo 'Setup finished.'"
  end
end